# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
a=torch.rand(7,7)
a


tensor([[0.0771, 0.3418, 0.5585, 0.8325, 0.2094, 0.6644, 0.7337],
        [0.2221, 0.8934, 0.0413, 0.9737, 0.8982, 0.0205, 0.4205],
        [0.1020, 0.0784, 0.4031, 0.1072, 0.0784, 0.8875, 0.3101],
        [0.4903, 0.2234, 0.9505, 0.7612, 0.5596, 0.4906, 0.6136],
        [0.9670, 0.5542, 0.4862, 0.3503, 0.4643, 0.6537, 0.4915],
        [0.5190, 0.2873, 0.4833, 0.3131, 0.9313, 0.3062, 0.5352],
        [0.7849, 0.8833, 0.5200, 0.5321, 0.3741, 0.0186, 0.8880]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
b=torch.rand(1,7)
print(f'''{a}
{b}''')
# Perform matrix multiplication 
torch.matmul(a,b.T)

tensor([[0.0771, 0.3418, 0.5585, 0.8325, 0.2094, 0.6644, 0.7337],
        [0.2221, 0.8934, 0.0413, 0.9737, 0.8982, 0.0205, 0.4205],
        [0.1020, 0.0784, 0.4031, 0.1072, 0.0784, 0.8875, 0.3101],
        [0.4903, 0.2234, 0.9505, 0.7612, 0.5596, 0.4906, 0.6136],
        [0.9670, 0.5542, 0.4862, 0.3503, 0.4643, 0.6537, 0.4915],
        [0.5190, 0.2873, 0.4833, 0.3131, 0.9313, 0.3062, 0.5352],
        [0.7849, 0.8833, 0.5200, 0.5321, 0.3741, 0.0186, 0.8880]])
tensor([[0.1614, 0.0660, 0.0552, 0.8129, 0.6126, 0.2825, 0.9868]])


tensor([[1.7825],
        [1.8596],
        [0.7358],
        [1.8521],
        [1.4584],
        [1.5691],
        [1.7569]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
a,b=torch.rand((7,7)),torch.rand((1,7))

# Matrix multiply tensors
torch.matmul(a,b.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# !nvidia-smi

In [ ]:
gpu = "cuda" if torch.cuda.is_available() else "cpu"
gpu

'cuda'

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available(),'\n')
# Create two random tensors on GPU
a=torch.rand((2,3))
b=torch.rand((2,3))
print(f"""
Tensor: {a}, on: {a.device}
Tensor: {b}, on: {b.device}
""")
a=a.to(gpu)
b=b.to(gpu)

print(f"""
Tensor: {a}, on: {a.device}
Tensor: {b}, on: {b.device}
""")


True 


Tensor: tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]), on: cpu
Tensor: tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]), on: cpu


Tensor: tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0'), on: cuda:0
Tensor: tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0'), on: cuda:0




### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
adotb=torch.matmul(a,b.T)
adotb


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
# Find min
print(f'max: {adotb.max()}, min: {adotb.min()}')

max: 0.5617256760597229, min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
# Find arg min

print(f'index of max: {adotb.argmax()},index of min: {adotb.argmin()}')

index of max: 3,index of min: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
a=torch.rand((1,1,1,10))
# Remove single dimensions
a_1D=a.view(10)
# Print out tensors and their shapes
print(f'tensor: {a}, shape: {a.shape}')
print(f'tensor: {a_1D}, shape: {a_1D.shape}')

tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), shape: torch.Size([1, 1, 1, 10])
tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), shape: torch.Size([10])
